//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDT.Plugins.TransferStudentTracker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransferStudentTracker.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arena.
        /// </summary>
        public static string Arena {
            get {
                return ResourceManager.GetString("Arena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes the Arena game mode..
        /// </summary>
        public static string ArenaDescription {
            get {
                return ResourceManager.GetString("ArenaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brawl.
        /// </summary>
        public static string Brawl {
            get {
                return ResourceManager.GetString("Brawl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes brawls from Tavern Brawl and Fireside Gatherings..
        /// </summary>
        public static string BrawlDescription {
            get {
                return ResourceManager.GetString("BrawlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casual.
        /// </summary>
        public static string Casual {
            get {
                return ResourceManager.GetString("Casual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes the casual play mode..
        /// </summary>
        public static string CasualDescription {
            get {
                return ResourceManager.GetString("CasualDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly Play.
        /// </summary>
        public static string Friendly {
            get {
                return ResourceManager.GetString("Friendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes any game with a player on his/her friend list (Does not include Battlegrounds)..
        /// </summary>
        public static string FriendlyDescription {
            get {
                return ResourceManager.GetString("FriendlyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Modes.
        /// </summary>
        public static string GameModes {
            get {
                return ResourceManager.GetString("GameModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The various ways to play Hearthstone..
        /// </summary>
        public static string GameModesDescription {
            get {
                return ResourceManager.GetString("GameModesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice/Solo Adventures.
        /// </summary>
        public static string Practice {
            get {
                return ResourceManager.GetString("Practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes all modes in the Solo Adventure game mode such as Practice, Adventures, and Missions..
        /// </summary>
        public static string PracticeDescription {
            get {
                return ResourceManager.GetString("PracticeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranked.
        /// </summary>
        public static string Ranked {
            get {
                return ResourceManager.GetString("Ranked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes the ranked play mode..
        /// </summary>
        public static string RankedDescription {
            get {
                return ResourceManager.GetString("RankedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectator.
        /// </summary>
        public static string Spectator {
            get {
                return ResourceManager.GetString("Spectator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes the spectator mode (The gamemode of the player being spectated must also be enabled in order to start tracking.).
        /// </summary>
        public static string SpectatorDescription {
            get {
                return ResourceManager.GetString("SpectatorDescription", resourceCulture);
            }
        }
    }
}
